version: '3.8'
services:
  fastapi-app:
    build: 
      context: /chatbot_back-end
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - ./dependencies:/dependencies
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
